name: postownik
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^7.2.0
  langchain: ^0.0.3
  langchain_openai: ^0.0.3
  riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1

  build_runner: ^2.4.6
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.2.0
  go_router: ^10.0.0
  flutter_adaptive_scaffold: ^0.1.5
  flutter_facebook_auth: ^6.0.1
  http: ^1.1.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  mockito: ^5.4.2
  cached_network_image: ^3.2.3

  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  riverpod_generator: ^2.2.3
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/blank_profile_pic.jpg
    - assets/logo_postownik.png
    - assets/logo2.png


  uses-material-design: true

